spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.efhknbyeujumwlduldhh
spring.datasource.password=Raghul@2006$
spring.datasource.driver-class-name=org.postgresql.Driver

# Force Hikari to pass prepareThreshold=0 to the Postgres driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=NesamaniSuperSecretKey2026PlatformTamilNaduContractor
jwt.expiration=86400000